### PR TITLE
applications: add brianalyze

### PR DESCRIPTION
**Pull request by risicle**
It's a slightly creaky old application now, but still works fine and I realized I've never really publicized it.

### CODE REVIEW

**Comment by risicle** [comment]
I assume this propagates to jackaudio.org too eventually?

**Comment by mseeber** [comment]
Yes, I'd like to collect some more changes before rebuilding the site. I'll see to it in the next two weeks.

**Comment by risicle** [comment]
:thumbsup:

**Comment by mseeber** [comment]
This keeps on dragging as I can not push to the respective web space, but it will not be forgotten.

**Pull request merged**
