### PR TITLE
Add JackSharp and NAudio.Jack

### PR DESCRIPTION
**Pull request by residuum**
.NET and Mono bindings for jack.

### CODE REVIEW

**Comment by mseeber** [comment]
I am not that familiar with the .NET/mono ecosystem, is nuget the usual way to go for libraries there? I ask since the GitHub Readme has a lot more info on the software than the nuget page. Maybe it is more beneficial for your project to link to the GitHub repo instead of nuget? I don't know.

**Comment by residuum** [comment]
nuget ist pretty standard nowadays, but I have changed the link to the Github repo, because there is a link to nuget.

**Comment by mseeber** [comment]
OK, if in the future, you'd like t have the link changed to a location more appropriate just say so. My comment was just an idea after taking a first look.

**Comment by residuum** [comment]
OK, I will do that. I have just thought, that pull requests are the fastest and easiest way for you to add and change a library.

**Comment by mseeber** [comment]
Or you could send a pull request, that is possible too.

**Pull request merged**
